[package]
name = "apery"
version = "1.1.0"
authors = ["HiraokaTakuya <hiraoka64@gmail.com>"]
edition = "2018"

[dependencies]
arrayvec = "0.5.2"
custom_derive = "0.1.7"
derive_more = "0.99.11"
enum_derive = "0.1.7"
lazy_static = "1.4.0"
num = "0.3.1"
rand = "0.8.1"
rayon = "1.5.0"
regex = "1.4.2"
serde = { version = "1.0.118", features = ["derive"] }
serde_json = "1.0.61"

[profile.release]
lto = true
