[package]
name = "apery"
version = "1.0.2"
authors = ["HiraokaTakuya <hiraoka64@gmail.com>"]
edition = "2018"

[dependencies]
arrayvec = "*"
custom_derive = "*"
derive_more = "*"
enum_derive = "*"
lazy_static = "*"
num = "*"
rand = "*"
rayon = "*"
regex = "*"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
