[package]
name = "apery"
version = "1.1.0"
authors = ["HiraokaTakuya <hiraoka64@gmail.com>"]
edition = "2018"

[dependencies]
arrayvec = "0.7.1"
custom_derive = "0.1.7"
derive_more = "0.99.16"
enum_derive = "0.1.7"
num = "0.4.0"
once_cell = "1.8.0"
rand = "0.8.4"
rayon = "1.5.1"
regex = "1.5.4"
serde = { version = "1.0.127", features = ["derive"] }
serde_json = "1.0.66"
static_assertions = "1.1.0"

[profile.release]
lto = true

[features]
default = ["kppt"]
kppt = []
material = []
